// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get the environment variables
const supabaseUrl = process.env.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Create the Supabase client
export const supabase = createClient(
  supabaseUrl || 'https://fpkkfuxdleqdlstrexzy.supabase.co',
  supabaseAnonKey || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwa2tmdXhkbGVxZGxzdHJleHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzgwMTMsImV4cCI6MjA1OTAxNDAxM30.rdO86r5YuyEe8JJN-K6yifNTSlyF_haynD3jjNpHkhg'
);

// Test the connection
const testConnection = async () => {
  try {
    const { data, error } = await supabase.from('tea_shops').select('*').limit(1);
    if (error) {
      console.error('Supabase connection error:', error);
    } else {
      console.log('Supabase connection successful!');
    }
  } catch (error) {
    console.error('Supabase connection error:', error);
  }
};

// Run the connection test
testConnection();